import {v4 as uuid} from "react";

/**
 * Videos Database can be added here.
 * You can add videos of your wish with different attributes
 * */

export const videos = [
  {
    // 3 MUSIC
    _id: uuid(),
    title: 'Dua Lipa - Levitating Featuring DaBaby (Official Music Video)',
    description: "The official music video for Dua Lipa - Levitating featuring @DaBaby \n\nTaken from her second studio album 'Future Nostalgia' released in 2020, which featured the hit singles 'Don't Start Now', 'Physical', 'Break My Heart'",
    creator: 'Dua Lipa',
    logo: 'https://yt3.ggpht.com/ytc/AKedOLRjI68131sY_h0hUZkGgxqMDlKe-IosbR65zo476A=s88-c-k-c0x00ffffff-no-rj-mo',
    thumbnail: 'https://i.ytimg.com/vi/TUVcZfQe-Kw/default.jpg',
    views: '110k',
    createdAt: '12 May 2022',
    src: 'https://www.youtube.com/embed/PumNp_O_Euo',
    category: 'music',
    duration: '5:58',
  },
  {
    _id: uuid(),
    title: 'Alan Walker - Faded',
    description: 'Click below to listen to the first part of my new album, Walkerverse Pt. 1: https://alanwalker.lnk.to/WalkerversePt1\n\n△ Merch @  https://store.alanwalker.no △\n\nWalkers! Thanks for listening. If you want to hear my newest single and the last video in the World of Walker trilogy, \"Heading Home,\" check out the official music video here: https://youtu.be/mfSU_XwEnZA & the LIVE performance',
    creator: 'Alan Walker',
    logo: 'https://yt3.ggpht.com/aVVgun46AV1oXiN5TJh3lmsuWr2bKU2LW1163WB0GsZrthm4wfof6Lq8OVH5qOLq9zOQg8yj=s88-c-k-c0x00ffffff-no-nd-rj',
    thumbnail: 'https://i.ytimg.com/vi/60ItHLz5WEA/default.jpg',
    views: '110k',
    createdAt: '12 May 2022',
    src: 'https://www.youtube.com/watch?v=60ItHLz5WEA',
    category: 'music',
    duration: '6:58',
  },
 {
   _id: uuid(),
   title: 'Ed Sheeran - Perfect (Official Music Video)',
   description: "The official music video for Ed Sheeran - Perfect \nThe new album \"=\" is out now - listen here: https://es.lnk.to/equals\n \nTaken from the studio album ÷ (divide) released in 2017, which featured the hit singles 'Castle on the Hill', 'Shape of You', 'Galway Girl', ‘Perfect’ & 'Happier'. \n \nSubscribe to the Ed Sheeran channel for all the best and latest official music videos",
   creator: 'Ed Shareen',
   logo: 'https://yt3.ggpht.com/-syoRcPPGt3NE3TzbKJsefa5Rej4w_lSof-aXSm1Q9cDx5Gyn-Cuus8UKjKBtILs_Bqwgc_i0A=s88-c-k-c0x00ffffff-no-nd-rj',
   thumbnail: 'https://i.ytimg.com/vi/2Vv-BfVoq4g/default.jpg',
   views: '110k',
   createdAt: '12 May 2022',
   src: 'https://www.youtube.com/watch?v=2Vv-BfVoq4g',
   category: 'music',
   duration: '6:58',
 }, 
    //3 CODING
 {
   _id: uuid(),
   title: "Closures in JS 🔥 | Namaste JavaScript Episode 10",
   description: "Closures in JavaScript is the most important topic for interviews. Even many senior frontend developers don't understand this concept properly.  This video will clear all your doubts about closures in js and you will never have to find any other tutorial after this to understand function Closure and Garbage collection.",
   creator: 'Akshay Saini',
   logo: 'https://yt3.ggpht.com/ytc/AKedOLR8gqN3fHHNYbehMcsJ49rapBPhJMGPYSrl6YQyNg=s88-c-k-c0x00ffffff-no-rj',
   thumbnail: 'https://i.ytimg.com/vi/qikxEIxsXco/default.jpg',
   views: '110k',
   createdAt: '12 May 2022',
   src: 'https://www.youtube.com/watch?v=qikxEIxsXco',
   category: 'coding',
   duration: '5:58',
 },
 {
   _id: uuid(),
   title: "JavaScript Crash Course For Beginners",
   description: "In this crash course we will go over the fundamentals of JavaScript including more modern syntax like classes, arrow functions, etc.This is the starting point on my channel for learning JS.\n\ nCode including html / css: \nhttps: //embed.plnkr.co/plunk/8ujYdL1BxZftGoS4Cf14\n\n21 Hour JavaScript Course",
   creator: 'Traversy Media',
   logo: 'https://yt3.ggpht.com/ytc/AKedOLSxHOOxxa9Af8Bfb2XMop3lm4tor9bViWiC-d5aaw=s88-c-k-c0x00ffffff-no-rj',
   thumbnail: 'https://i.ytimg.com/vi/hdI2bqOjy3c/default.jpg',
   views: '110k',
   createdAt: '12 May 2022',
   src: 'https://www.youtube.com/watch?v=hdI2bqOjy3c',
   category: 'coding',
   duration: '5:58',
 },
 {
   _id: uuid(),
   title: "5 Design Patterns Every Engineer Should Know",
   description: "In this video we will talk about some important software design patterns\n\nJack Herrington YouTube Channel:\nhttps://www.youtube.com/channel/UC6vRUjYqDuoUsYsku86Lrsw\n\nTimestamps:\n0:00 - Intro\n2:14 - Singleton Pattern\n3:51 - Facade Pattern\n5:48 - Bridge/Adapter Pattern\n8",
   creator: 'Traversy Media',
   logo: "https://yt3.ggpht.com/ytc/AKedOLSxHOOxxa9Af8Bfb2XMop3lm4tor9bViWiC-d5aaw=s88-c-k-c0x00ffffff-no-rj",
   thumbnail: "https://i.ytimg.com/vi/FLmBqI3IKMA/default.jpg",
   views: '110k',
   createdAt: '12 May 2022',
   src: 'https://www.youtube.com/watch?v=FLmBqI3IKMA',
   category: 'coding',
   duration: '5:58',
 },

  // 3 NATURE
{
  _id: uuid(),
  title: "Switzerland in 8K ULTRA HD HDR - Heaven of Earth (60 FPS)",
  description: "Swiss town with lake and nice palm tree 6: 30\ n27.Geneva City with lake in Switzerland 7: 01\ n28.Farm with cows eating grass in the field 7: 22\ n29.Lucerne City in Switzerland 7: 35\ n30.Geneva City with green beautiful mountain in Switzerland 7: 51\ n31.Geneva City in Switzerland(part 2) 8: 04\ n32.Matterhorn with blue sky and clouds 8: 24\ n33.Green Tree and mountain with little river 8: 42\ n34.Narrow roads and cars are moving along the side of the hill 8: 54\ n35.Lucerne City in Switzerland 9: 18\ n36.red glacier express in Switzerland alps 9: 31\ n37.",
  creator: '8K World',
  logo: "https://yt3.ggpht.com/ytc/AKedOLSS1lyM1dY-UqjVb023wncf64ON14K9N6zQwSVH=s88-c-k-c0x00ffffff-no-rj",
  thumbnail: "https://i.ytimg.com/vi/linlz7-Pnvw/default.jpg",
  views: '110k',
  createdAt: '12 May 2022',
  src: 'https://www.youtube.com/watch?v=linlz7-Pnvw',
  category: 'nature',
  duration: '5:58',
},
{
  _id: uuid(),
  title: "Chinese online star Li Ziqi provides an escape from urban life",
  description: "Subscribe to our YouTube channel for free here: \nhttps://sc.mp/subscribe-youtube\n\nChinese online star Li Ziqi has become one of the most famous internet celebrities in the country by sharing videos of her rural life. She picks ingredients from her farm, constructs furniture by hand and cooks a vast spread, providing a respite from busy urban living for her tens of millions of fans worldwide.\n\nFollow us on:\nWebsite:  https://scmp.com\nFacebook",
  creator: 'South China Morning Post',
  logo: "https://yt3.ggpht.com/ytc/AKedOLR5u-P-n-9CDMgBsxorfnZH41bdvP13qnXcpnsDTg=s88-c-k-c0x00ffffff-no-rj",
  thumbnail: "https://i.ytimg.com/vi/r6z_ia0L7Wc/default.jpg",
  views: '110k',
  createdAt: '12 May 2022',
  src: 'https://www.youtube.com/watch?v=r6z_ia0L7Wc',
  category: 'nature',
  duration: '5:58',
},
{
  _id: uuid(),
  title: "Gooey sweet potatoes&hand-made noodles, in hot and sour soup|Liziqi",
  description: "Liziqi channel—— roast sweet potato and  spicy and sour noodles\n烤红薯的香甜和酸辣粉的鲜辣，暖冬好滋味\n\n挖了红薯做够大半年要用的淀粉，\n再囤一点宽粉 细苕粉应付这个冬季。\n冰雪天，来上一碗麻辣鲜香的手工酸辣粉\n饭后再整俩又香又甜的烤红薯。\n一边在雪地里蹦跶一边吐着烤红薯的热气！\n呼…………\n\nNewly dug-out sweet potatoes, enough to make starch for half a year’s use.\nMake some into noodles wide or thin, and stock up for the winter.\nIn snowy days, have a bowl of such hand-made noodles, in hot and sour soup.\nAnd roast two more gooey sweet potatoes.\nOh, I can see my sweet hot breath in the snow.\nHot! hu h",
  creator: 'Liziqi',
  logo: "https://yt3.ggpht.com/ytc/AKedOLSIVX8gVv9IlIO5u3qSueSEB4C_zgqCxy66BEdq0A=s88-c-k-c0x00ffffff-no-rj",
  thumbnail: "https://i.ytimg.com/vi/yMRiUPzp0RY/default.jpg",
  views: '110k',
  createdAt: '12 May 2022',
  src: 'https://www.youtube.com/watch?v=yMRiUPzp0RY',
  category: 'nature',
  duration: '5:58',
},


];
